//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektWPF.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektWPF.Languages.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        public static string btnDalje {
            get {
                return ResourceManager.GetString("btnDalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispis.
        /// </summary>
        public static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi sliku.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string gumbSpremi {
            get {
                return ResourceManager.GetString("gumbSpremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite prvenstvo.
        /// </summary>
        public static string izaberiPrvenstvo {
            get {
                return ResourceManager.GetString("izaberiPrvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite najdraže igrače.
        /// </summary>
        public static string izaberiteNajdrazeIgrace {
            get {
                return ResourceManager.GetString("izaberiteNajdrazeIgrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite najdražu naciju.
        /// </summary>
        public static string izabertiNajdražuNaciju {
            get {
                return ResourceManager.GetString("izabertiNajdražuNaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string izadiIzAplikacije {
            get {
                return ResourceManager.GetString("izadiIzAplikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posjećenost:.
        /// </summary>
        public static string lbAttendance {
            get {
                return ResourceManager.GetString("lbAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost:.
        /// </summary>
        public static string lbAwayTeam {
            get {
                return ResourceManager.GetString("lbAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorit:.
        /// </summary>
        public static string lbFavourite {
            get {
                return ResourceManager.GetString("lbFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi:.
        /// </summary>
        public static string lbGolovi {
            get {
                return ResourceManager.GetString("lbGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gubici:.
        /// </summary>
        public static string lbGubici {
            get {
                return ResourceManager.GetString("lbGubici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin:.
        /// </summary>
        public static string lbHomeTeam {
            get {
                return ResourceManager.GetString("lbHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod:.
        /// </summary>
        public static string lbKod {
            get {
                return ResourceManager.GetString("lbKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string lblBroj {
            get {
                return ResourceManager.GetString("lblBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrane:.
        /// </summary>
        public static string lbOdigrani {
            get {
                return ResourceManager.GetString("lbOdigrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede:.
        /// </summary>
        public static string lbPobjede {
            get {
                return ResourceManager.GetString("lbPobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni:.
        /// </summary>
        public static string lbPrimljeni {
            get {
                return ResourceManager.GetString("lbPrimljeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika:.
        /// </summary>
        public static string lbRazlika {
            get {
                return ResourceManager.GetString("lbRazlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        public static string lbVenue {
            get {
                return ResourceManager.GetString("lbVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Više....
        /// </summary>
        public static string lbVise {
            get {
                return ResourceManager.GetString("lbVise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni:.
        /// </summary>
        public static string lbZabijeni {
            get {
                return ResourceManager.GetString("lbZabijeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni:.
        /// </summary>
        public static string lbZuti {
            get {
                return ResourceManager.GetString("lbZuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika spremljena.
        /// </summary>
        public static string mbSave {
            get {
                return ResourceManager.GetString("mbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string postavkeToolStripMenuItem {
            get {
                return ResourceManager.GetString("postavkeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string promijeniJezikToolStripMenuItem {
            get {
                return ResourceManager.GetString("promijeniJezikToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni naciju i jezik.
        /// </summary>
        public static string promijeniNacijuToolStripMenuItem {
            get {
                return ResourceManager.GetString("promijeniNacijuToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni natjecanje.
        /// </summary>
        public static string promijeniNatjecanjeToolStripMenuItem {
            get {
                return ResourceManager.GetString("promijeniNatjecanjeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalno tri favorita.
        /// </summary>
        public static string triIgrača {
            get {
                return ResourceManager.GetString("triIgrača", resourceCulture);
            }
        }
    }
}
